### ISSUE TITLE
Throws error when distance provided in feet

### ISSUE THREAD

**Issue by clementallen** [Turbo87/cup-parser#149]
I can see a specific test to check that an error is thrown, but in the UK we have `.cup` files with distance in feet so it would be useful to support this.

I am happy to make the changes if it's okay to change this behaviour?

Example file: https://gist.github.com/clementallen/8c8aa9c1519d0e39ceacd5a679a86f63

**Comment by Turbo87** [comment]
if you look at https://github.com/Turbo87/cup-parser/blob/master/docs/cup_format.pdf, it explicitly lists the valid units that can be used for the runway length, and `ft` is not listed there

**Comment by clementallen** [comment]
I appreciate that the specification does not state that `ft` is a recognised unit, but it is in use so I think it should be supported
